name: test proj
on: push
jobs:
  first_job_test:
    runs-on: ubuntu-latest
    steps:
      name: Test
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
          python-version: "3.10"
      name: Install requirement
        -run: pip install -r requirements.txt
      
        - run: python main.py
