name: test proj
on: push
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: SetUp Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: |
            **/setup.cfg
            **/requirements*.txt
      - run: pip install -r requirements.txt
      #- name: Install dependencies
        #if: steps.chached_libraries.outputs.cache-hit != 'true'
       # run: pip install -r requirements.txt
      - name: Run tests
        run: python test_main.py
  run_code:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: SetUp Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: |
            **/setup.cfg
            **/requirements*.txt
      - run: pip install  -r requirements.txt
      - name: Run main code
        run: python main.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pictures
          path: pictures
        
  deploy:
    needs: run_code
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with: 
          name: pictures
        
      - name: Output contents
        run: ls
        

