name: test proj
on: push
jobs:
  first_job_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: intstall python
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip" # caching pip dependencies
    - name: run code
      - run:  pip install -r requirements.txt
 
